return {
	Accent = Color3.fromRGB(82, 201, 255),

	AcrylicMain = Color3.fromRGB(21, 25, 31),
	AcrylicBorder = Color3.fromRGB(56, 66, 82),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(18, 22, 27), Color3.fromRGB(24, 29, 36)),
	AcrylicNoise = 0.93,

	TitleBarLine = Color3.fromRGB(44, 51, 62),
	Tab = Color3.fromRGB(44, 53, 67),

	Element = Color3.fromRGB(50, 60, 75),
	ElementBorder = Color3.fromRGB(25, 30, 38),
	InElementBorder = Color3.fromRGB(72, 84, 103),
	ElementTransparency = 0.76,

	ToggleSlider = Color3.fromRGB(84, 96, 114),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(76, 88, 106),

	DropdownFrame = Color3.fromRGB(67, 79, 98),
	DropdownHolder = Color3.fromRGB(20, 24, 30),
	DropdownBorder = Color3.fromRGB(27, 32, 40),
	DropdownOption = Color3.fromRGB(61, 72, 88),

	Keybind = Color3.fromRGB(58, 69, 86),

	Input = Color3.fromRGB(54, 63, 78),
	InputFocused = Color3.fromRGB(15, 18, 24),
	InputIndicator = Color3.fromRGB(99, 112, 132),

	Dialog = Color3.fromRGB(18, 22, 28),
	DialogHolder = Color3.fromRGB(24, 29, 36),
	DialogHolderLine = Color3.fromRGB(31, 37, 46),
	DialogButton = Color3.fromRGB(28, 34, 42),
	DialogButtonBorder = Color3.fromRGB(73, 87, 108),
	DialogBorder = Color3.fromRGB(55, 66, 82),
	DialogInput = Color3.fromRGB(33, 39, 49),
	DialogInputLine = Color3.fromRGB(96, 110, 131),

	Text = Color3.fromRGB(241, 245, 249),
	SubText = Color3.fromRGB(154, 166, 183),
	Hover = Color3.fromRGB(76, 90, 111),
	HoverChange = 0.05
}
